from . import odoo16_database_base
from . import odoo16_database_coordinator
from . import migration_users_partners
from . import migration_mail_system
from . import migration_calendar_events
from . import migration_attachments
from . import migration_ir_filters
from . import migration_sports_teams
from . import migration_sports_patients
from . import migration_sports_injuries
from . import migration_activities
from . import res_partner
from . import res_users
from . import sports_patient
from . import sports_patient_injury
