from . import account_account_etl
from . import product_pricelist_etl
from . import res_partner_etl
from . import product_category_etl
from . import product_template_etl
from . import product_pricelist_item_etl
from . import account_journal_etl
from . import account_move_open_item_etl
from . import account_payment_etl
from . import account_move_counter_entry_etl
from . import account_move_opening_balance_etl
from . import account_move_journal_entry_etl
from . import account_move_year_end_close_etl
