"""QBO post-posting GL correction (Journal export truth).

After `qbo.gl.first.import` posts typed invoices/bills/refunds, Odoo may
recompute accounts during `action_post()`. This pipeline corrects them back
to the authoritative postings from the QBO Journal export.

Two correction modes:

1. **qbo_acct_id** — Safety net for product lines: re-checks all enriched
   moves and SQL-updates any remaining lines where ``account_id != qbo_acct_id``.

2. **Journal export AR/AP** — For payment_term lines whose account was
   auto-generated by ``action_post()``, the pipeline parses the Journal
   export to determine the correct AR/AP account and updates it.
"""

import base64
import logging
from typing import Dict, List, Optional, Tuple

from odoo import models

from odoo.addons.etl_framework import ETL, ETLContext

from .gl_import_etl import _parse_journal_export

_logger = logging.getLogger(__name__)

_ENRICHABLE_TYPES = {"Invoice", "Bill", "Credit Memo", "Vendor Credit"}

_QBO_ID_FIELD_MAP = {
    "Invoice": "qbo_invoice_id",
    "Bill": "qbo_bill_id",
    "Credit Memo": "qbo_credit_memo_id",
    "Vendor Credit": "qbo_vendor_credit_id",
}


@ETL.pipeline(
    target_model="account.move",
    importer_name="qbo.gl.correction",
    sap_source="GLExport",
    depends_on=["qbo.gl.first.import"],
)
class QboGlCorrection(models.AbstractModel):
    _name = "qbo.gl.correction"
    _description = "QBO GL correction for product line accounts and AR/AP"

    @ETL.extract("GLExport")
    def extract_gl_truth(self, ctx: ETLContext) -> Dict:
        # Phase 1: Fix any remaining qbo_acct_id mismatches (product lines).
        ctx.env.cr.execute(
            """
            UPDATE account_move_line
               SET account_id = qbo_acct_id
             WHERE qbo_acct_id IS NOT NULL
               AND account_id <> qbo_acct_id
            """
        )
        fixed = ctx.env.cr.rowcount
        if fixed:
            ctx.env.invalidate_all()
            _logger.info(f"Phase 1: restored {fixed} product line accounts from qbo_acct_id")
        else:
            _logger.info("Phase 1: all qbo_acct_id lines already correct")

        # Phase 2: Parse Journal export for AR/AP truth.
        connection = ctx.env["qbo.connection"].browse(ctx.get_config("source_id"))
        if not connection.gl_export_file:
            _logger.info("No Journal export — skipping phase 2 AR/AP correction")
            return {"txns": {}}

        file_content = base64.b64decode(connection.gl_export_file)
        transactions = _parse_journal_export(file_content)

        # Account code -> (account_id, account_type)
        ctx.env.cr.execute(
            """
            SELECT aa.id,
                   aa.code_store::jsonb->>jsonb_object_keys(aa.code_store::jsonb) as code,
                   aa.account_type
            FROM account_account aa
            """
        )
        code_to_account: Dict[str, Tuple[int, str]] = {}
        for acc_id, code, acc_type in ctx.env.cr.fetchall():
            if code:
                code_to_account[str(code)] = (acc_id, acc_type)
                # Also register with suffixes for deduped codes.
                for suffix in (".1", ".2", ".3"):
                    key = str(code) + suffix
                    if key not in code_to_account:
                        break

        def resolve_code(code: str) -> Optional[Tuple[int, str]]:
            if code in code_to_account:
                return code_to_account[code]
            for suffix in (".1", ".2", ".3"):
                key = code + suffix
                if key in code_to_account:
                    return code_to_account[key]
            return None

        txns: Dict[str, Dict] = {}
        for t in transactions:
            txn_id = str(t.get("id"))
            lines = t.get("lines") or []
            if not lines:
                continue
            txn_type = str(lines[0].get("type") or "")
            if txn_type not in _ENRICHABLE_TYPES:
                continue

            arap_candidates: List[Tuple[float, int]] = []

            for ld in lines:
                code = str(ld.get("account_code") or "").strip()
                resolved = resolve_code(code)
                if not resolved:
                    continue
                account_id, account_type = resolved
                balance = float(ld.get("debit") or 0.0) - float(ld.get("credit") or 0.0)
                if account_type in ("asset_receivable", "liability_payable"):
                    arap_candidates.append((abs(balance), account_id))

            arap_account_id = None
            if arap_candidates:
                arap_account_id = sorted(
                    arap_candidates, key=lambda x: x[0], reverse=True
                )[0][1]

            if arap_account_id:
                txns[txn_id] = {
                    "type": txn_type,
                    "arap_account_id": arap_account_id,
                }

        _logger.info(f"Phase 2: prepared GL truth for {len(txns)} enrichable transactions")
        return {"txns": txns}

    @ETL.transform()
    def transform_gl_corrections(self, ctx: ETLContext, extracted: Dict) -> List[Dict]:
        data = extracted.get("extract_gl_truth", {})
        txns = data.get("txns", {}) or {}
        if not txns:
            return []

        # Find posted enriched moves.
        Move = ctx.env["account.move"]
        domain_parts = []
        for txn_type, field in _QBO_ID_FIELD_MAP.items():
            ids = [int(k) for k, v in txns.items() if v["type"] == txn_type and k.isdigit()]
            if ids:
                domain_parts.append((field, "in", ids))

        if not domain_parts:
            return []

        # Build OR domain: prefix with (N-1) "|" operators for N conditions.
        or_domain = []
        for _ in range(len(domain_parts) - 1):
            or_domain.append("|")
        or_domain.extend(domain_parts)

        moves = Move.search([("state", "=", "posted")] + or_domain)
        _logger.info(f"Phase 2: found {len(moves)} posted enrichable moves to check")

        corrections = []
        for move in moves:
            txn_id = None
            for field in _QBO_ID_FIELD_MAP.values():
                val = getattr(move, field, 0)
                if val:
                    txn_id = str(val)
                    break
            if not txn_id or txn_id not in txns:
                continue
            truth = txns[txn_id]
            corrections.append({
                "move_id": move.id,
                "arap_account_id": truth.get("arap_account_id"),
            })

        return corrections

    @ETL.load()
    def load_apply_corrections(self, ctx: ETLContext, transformed: Dict) -> None:
        corrections = transformed.get("transform_gl_corrections", [])
        if not corrections:
            _logger.info("Phase 2: no AR/AP corrections needed")
            return

        Move = ctx.env["account.move"]
        applied_arap = 0

        for corr in corrections:
            move = Move.browse(corr["move_id"])
            if not move.exists():
                continue

            arap_account_id = corr.get("arap_account_id")
            if arap_account_id:
                for line in move.line_ids:
                    if line.display_type == "payment_term" and line.account_id.id != arap_account_id:
                        ctx.env.cr.execute(
                            "UPDATE account_move_line SET account_id = %s WHERE id = %s",
                            (arap_account_id, line.id),
                        )
                        applied_arap += 1

        if applied_arap:
            ctx.env.invalidate_all()

        _logger.info(f"Phase 2: applied AR/AP corrections — {applied_arap}")
