from . import test_odoo16_database_base
from . import test_migration_users_partners
from . import test_migration_mail_system
from . import test_migration_calendar_events
from . import test_migration_attachments
from . import test_migration_ir_filters
from . import test_migration_sports_teams
from . import test_migration_sports_patients
from . import test_migration_sports_injuries
from . import test_odoo16_database_coordinator
from . import test_integration_migration
from . import test_users_partners_migration_focused
from . import test_comprehensive_migration
from . import test_patient_migration_debug
from . import test_patient_migration_isolated
from . import test_partner_lookup_debug
from . import test_partner_migration_verification
from . import test_partner_staff_debug
